travis:
  secure:
    BINSTAR_TOKEN: SbYdyBtV3AHiktF6avo0L7OHOGvQ+013He7wGt7kfMOAhHvYnzE1HNHVAxr8hv5v1IyHdqgxlzUZi9mADZmY3T7m4c/P1RpnO/jJj531OCTOYIvesfOLwBnKg0zLdPlwjZ/e8hXgi93roiJrTH5t6i3SQUtQnPzWHCwxiJecJFf2ldqmXefXJaMpzLKeZ5zshRohCcoAhF8ozUmYpOBrkIUJg5a/STRoIw8MtwUSlbe8ixgL86O64vsuGRxsxeoVxCaPc8lteKVsUZboGVWRJsnb58G9ezMZrPpeZ+OZkdH4CZ/IuAgZFtzWYKCGyNuX7vgq6IYHomq1hfM+c2PHtlIYib21BBAALS+DP73ctU7rSNynY8mO04ROgQTX8vgeCJ8WD81gm+0OY/BLD8XZ9LSV7/Ux6q+6TuDigM1xQxLC85zMQOBaxE7vhEok5CdhJqPfugy9j5QP/redjvbLH/U8iUmR3qpPohzTAOKmz1bNvCrSacQ9HaLJQ//+zhKi4eZB9NrUrFYD7cIhr6XY5yPKbiKRR3PaWQGI0cN9prUlo+5BVh1EQ+kd0Z/C5lTWE6hlSnXjulACUMQQlT4gkUNnhEbdfaIl5Jp8x09CXmcmCJnk/v6r5Y7HcZIP0xsrpFrXTIy7I4bHLCBMkPl0puAGIP0XA6h/CSzRTe3EJnA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
