travis:
  secure:
    BINSTAR_TOKEN: IlJLlp43kI6bpIicAagC9LkKknQRR8Ipquri0yATyKKUj1x5am+pFnkeWtNuCZ8UuuEX3SuwN9t8T7xmv0bxMFpemv1W6iPdk4HEkUkyb3/YyMXHSCByeg/+fjX88JciynPNVjA29CM4OcAftwpACmcrtVfA02FIXl3brULh4mLAYztyggvGK28TmGX5JlXffk1Of/eyCYSAH+4C5v6q9Knx5WVZxpDopLyiTfIEWCVMResxnmePglgclJIJ/PIpLa49U10Kiu/oA48eDXxpuupuLsLSvyZPEH9H+y6RkYYWLqI8iyOZDnTxB9HGY7GQRjve0s/MB8s4Hy0q95Fz7yu1Qq3z2Y4an04IlpnsJ5BS+pICukbouAdjMZ+hxjnUWVpZLfyi1z3D/UA2lQOKQOStKM5aIgIeISoeuJcNQG869ilq8LxL+/Pu/jJe0rhUUxdQsG+Gb/uws72xZsNCDXMYZQfUrBZGbVKNodLwIG044/qwxbt4LePK2b9Gk9HjOoH/zy3aIN5kEa6Jp5FyONMzB7PhwtHxnYA/pqK6wvMXonJ18u6lLGtIYVpGvBc3uFCNgcDAAOfqp7nacNzKhnOi0qqPCk0UyZall92+VClpZeO6bT0Qj6skTd55qTzxiEt12UQKIuKV2jKoqJtPgYhk5qX4gn9GWUTvGh+5mgk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
